; common config
[common]
mnt_path = "/mnt/sd/"


; dtcf config
[dtcf]
root_path          = "CARDV"
pre_alloc_cnt      = "100";
pre_alloc_unit     = "3110400";unit: byte
sharepercent       = 95
warning            = 4
guaranteed         = 5

[dir_name]
dir_name0 = "EMR_F"
dir_name1 = ""
dir_name2 = "MOVIE_F"
dir_name3 = ""
dir_name4 = ""
dir_name5 = ""
dir_name6 = "EMR_R"
dir_name7 = ""
dir_name8 = "MOVIE_R"
dir_name9 = ""
dir_name10 = ""
dir_name11 = ""
dir_name12 = "PHOTO_F"
dir_name13 = "PHOTO_R"
dir_name14 = ""
dir_name15 = ""
dir_name16 = ""
dir_name17 = ""
dir_name18 = ""
dir_name19 = ""
dir_name20 = ""

[prealloc]
enable = 0
reserve_memory = 5 ;percentage
pre_alloc_cnt_dir_0       = "10"; percentage
pre_alloc_unit_dir_0      = "40";unit: MB
pre_alloc_cnt_dir_1       = "";
pre_alloc_unit_dir_1      = "";unit: MB
pre_alloc_cnt_dir_2       = "40"; percentage
pre_alloc_unit_dir_2      = "100";unit: MB
pre_alloc_cnt_dir_3       = "";
pre_alloc_unit_dir_3      = "";unit: MB
pre_alloc_cnt_dir_4       = "";
pre_alloc_unit_dir_4      = "";unit: MB
pre_alloc_cnt_dir_5       = "";
pre_alloc_unit_dir_5      = "";unit: MB
pre_alloc_cnt_dir_6       = "10";percentage
pre_alloc_unit_dir_6      = "40";unit: MB
pre_alloc_cnt_dir_7       = "";
pre_alloc_unit_dir_7      = "";unit: MB
pre_alloc_cnt_dir_8       = "30";percentage
pre_alloc_unit_dir_8      = "80";unit: MB
pre_alloc_cnt_dir_9       = "";
pre_alloc_unit_dir_9      = "";unit: MB
pre_alloc_cnt_dir_10      = "";
pre_alloc_unit_dir_10     = "";unit: MB
pre_alloc_cnt_dir_11      = "";
pre_alloc_unit_dir_11     = "";unit: MB
pre_alloc_cnt_dir_12      = "5";percentage
pre_alloc_unit_dir_12     = "2";unit: MB
pre_alloc_cnt_dir_13      = "5";percentage
pre_alloc_unit_dir_13     = "2";unit: MB
pre_alloc_cnt_dir_14      = "";percentage
pre_alloc_unit_dir_14     = "";unit: MB
pre_alloc_cnt_dir_15      = "";percentage
pre_alloc_unit_dir_15     = "";unit: MB
pre_alloc_cnt_dir_16      = "";percentage
pre_alloc_unit_dir_16     = "";unit: MB
pre_alloc_cnt_dir_17      = "";percentage
pre_alloc_unit_dir_17     = "";unit: MB
pre_alloc_cnt_dir_18      = "";percentage
pre_alloc_unit_dir_18     = "";unit: MB
pre_alloc_cnt_dir_19      = "";percentage
pre_alloc_unit_dir_19     = "";unit: MB
pre_alloc_cnt_dir_20      = "";percentage
pre_alloc_unit_dir_20     = "";unit: MB
