#ifndef __CVI_PLAYBACKMNG_H__
#define __CVI_PLAYBACKMNG_H__

#include "cvi_appcomm.h"
#ifdef SERVICES_PLAYER_ON
#include "cvi_player_service.h"
#endif

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif /* End of #ifdef __cplusplus */

#define AMPLIFIER_ON 1
#define AMPLIFIER_OFF 0

/** Error Code */
#define CVI_PLAYBACKMNG_EINVAL          CVI_APPCOMM_ERR_ID(CVI_APP_MOD_PLAYBACKMNG, CVI_EINVAL)                  /**<Invalid argument */
#define CVI_PLAYBACKMNG_ENOTINIT        CVI_APPCOMM_ERR_ID(CVI_APP_MOD_PLAYBACKMNG, CVI_ENOINIT)                 /**<Not inited */
#define CVI_PLAYBACKMNG_EINITIALIZED    CVI_APPCOMM_ERR_ID(CVI_APP_MOD_PLAYBACKMNG, CVI_EINITIALIZED)            /**<Already Initialized */
#define CVI_PLAYBACKMNG_EINTER          CVI_APPCOMM_ERR_ID(CVI_APP_MOD_PLAYBACKMNG, CVI_EINTER)                  /**<Already Initialized */
#define CVI_PLAYBACKMNG_EREGISTER_EVENT CVI_APPCOMM_ERR_ID(CVI_APP_MOD_PLAYBACKMNG, CVI_ERRNO_CUSTOM_BOTTOM)     /**<register event failed */
#define CVI_PLAYBACKMNG_EMAXINSTANCE    CVI_APPCOMM_ERR_ID(CVI_APP_MOD_PLAYBACKMNG, CVI_ERRNO_CUSTOM_BOTTOM + 1) /**<beyond maximum instance */
#define CVI_PLAYBACKMNG_ESTORAGE        CVI_APPCOMM_ERR_ID(CVI_APP_MOD_PLAYBACKMNG, CVI_ERRNO_CUSTOM_BOTTOM + 2) /**<storage interface error */

/** event ID define */
typedef enum cviEVENT_PLAYBACKMNG_E {
    CVI_EVENT_PLAYBACKMNG_FINISHED = CVI_APPCOMM_EVENT_ID(CVI_APP_MOD_PLAYBACKMNG, 0),
    CVI_EVENT_PLAYBACKMNG_PLAY,
    CVI_EVENT_PLAYBACKMNG_PROGRESS,
    CVI_EVENT_PLAYBACKMNG_PAUSE,
    CVI_EVENT_PLAYBACKMNG_RESUME,
    CVI_EVENT_PLAYBACKMNG_FILE_ABNORMAL,
    CVI_EVENT_PLAYBACKMNG_BUTT
} CVI_EVENT_PLAYBACKMNG_E;

#ifndef SERVICES_PLAYER_ON
typedef void* CVI_PLAYER_SERVICE_HANDLE_T;
typedef enum
{
    CVI_PLAYER_SERVICE_EVENT_UNKNOWN,
    CVI_PLAYER_SERVICE_EVENT_OPEN_FAILED,
    CVI_PLAYER_SERVICE_EVENT_PLAY,
    CVI_PLAYER_SERVICE_EVENT_PLAY_FINISHED,
    CVI_PLAYER_SERVICE_EVENT_PLAY_PROGRESS,
    CVI_PLAYER_SERVICE_EVENT_PAUSE,
    CVI_PLAYER_SERVICE_EVENT_RESUME,
    CVI_PLAYER_SERVICE_EVENT_RECOVER_START,
    CVI_PLAYER_SERVICE_EVENT_RECOVER_PROGRESS,
    CVI_PLAYER_SERVICE_EVENT_RECOVER_FAILED,
    CVI_PLAYER_SERVICE_EVENT_RECOVER_FINISHED,
} CVI_PLAYER_SERVICE_EVENT_TYPE_E;

typedef struct
{
    CVI_PLAYER_SERVICE_EVENT_TYPE_E type;
    double value;
} CVI_PLAYER_SERVICE_EVENT_S;
#endif

void CVI_PLAYBACKMNG_EventCallBack(CVI_PLAYER_SERVICE_HANDLE_T hdl, CVI_PLAYER_SERVICE_EVENT_S *event_t);
int32_t CVI_PLAYBACKMNG_RegisterEvent(void);

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* End of #ifdef __cplusplus */

#endif /* End of __CVI_PLAYBACKMNG_H__ */