#ifndef __CVI_MODE_H__
#define __CVI_MODE_H__
#include "cvi_param.h"
#include "cvi_appcomm.h"
#include "cvi_hfsm.h"

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif /* __cplusplus */



typedef enum _CVI_WORK_MODE_E
{
    CVI_WORK_MODE_MOVIE,
    CVI_WORK_MODE_PHOTO,
    CVI_WORK_MODE_PLAYBACK,
    CVI_WORK_MODE_USBCAM,
    CVI_WORK_MODE_USB,
    CVI_WORK_MODE_UPDATE,
    CVI_WORK_MODE_LAPSE,
    CVI_WORK_MODE_UVC,
    CVI_WORK_MODE_STORAGE,
    CVI_WORK_MODE_BOOT,
    CVI_WORK_MODE_USBMENU,
    CVI_WORK_MODE_BUTT
} CVI_WORK_MODE_E;

typedef enum _CVI_MEDIA_MOVIE_MODE_E
{
    CVI_MEDIA_MOVIE_STATE_VIEW,
    CVI_MEDIA_MOVIE_STATE_REC,
    CVI_MEDIA_MOVIE_STATE_LAPSE_REC,
    CVI_MEDIA_MOVIE_STATE_MENU,
    CVI_MEDIA_MOVIE_STATE_BUTT
} CVI_MEDIA_MOVIE_MODE_E;

typedef enum _CVI_MEDIA_PHOTO_STATE_E
{
    CVI_MEDIA_PHOTO_STATE_VIEW,
    CVI_MEDIA_PHOTO_STATE_MENU,
    CVI_MEDIA_PHOTO_STATE_BUTT
} CVI_MEDIA_PHOTO_STATE_E;

typedef enum _CVI_MEDIA_PLAYBACK_STATE_E
{
    CVI_MEDIA_PLAYBACK_STATE_VIEW,
    CVI_MEDIA_PLAYBACK_STATE_PLAY,
    CVI_MEDIA_PLAYBACK_STATE_PAUSE,
    CVI_MEDIA_PLAYBACK_STATE_MENU,
    CVI_MEDIA_PLAYBACK_STATE_ABNORMAL,
    CVI_MEDIA_PLAYBACK_STATE_BUTT
} CVI_MEDIA_PLAYBACK_STATE_E;

/** exit mode */
typedef enum cviEXIT_MODE_E
{
    CVI_MODEMNG_EXIT_MODE_POWEROFF,
    CVI_MODEMNG_EXIT_MODE_REBOOT,
    CVI_MODEMNG_EXIT_MODE_SERVICE_QUIT,
    CVI_MODEMNG_EXIT_MODE_BUTT
} CVI_MODEMNG_EXIT_MODE_E;

typedef enum _CVI_CARD_STATE_E
{
    CVI_CARD_STATE_REMOVE,
    CVI_CARD_STATE_AVAILABLE,
    CVI_CARD_STATE_UNAVAILABLE,
    CVI_CARD_STATE_ERROR,
    CVI_CARD_STATE_FSERROR,
    CVI_CARD_STATE_CHECKING,
    CVI_CARD_STATE_SLOW,
    CVI_CARD_STATE_FORMATED,
    CVI_CARD_STATE_READ_ONLY,
    CVI_CARD_STATE_MOUNT_FAILED,
    CVI_CARD_STATE_BUIT
} CVI_CARD_STATE_E;

/** exit mode callback */
typedef int32_t (*CVI_MODEMNG_EXIT_MODE_CALLBACK)(CVI_MODEMNG_EXIT_MODE_E enExitMode);

/** statemng configure */
typedef struct cviPDT_MODEMNG_CONFIG_S
{
    CVI_MODEMNG_EXIT_MODE_CALLBACK pfnExitCB;
} CVI_MODEMNG_CONFIG_S;

/** modemng context */
typedef struct _CVI_MODEMNG_S {
    bool                bInited;
    pthread_mutex_t     Mutex;/**<Mutex for bInProgress*/
    CVI_HFSM_HANDLE     pvHfsmHdl;
    CVI_STATE_S         stBase;
    CVI_WORK_MODE_E     CurWorkMode;
    bool                bInProgress;
    bool                bInEmrRec;
    bool                bInParkingRec;
    bool                bSysPowerOff;
    uint8_t             u32ModeState;
    uint8_t             u32CardState;
    CVI_MODEMNG_CONFIG_S stModemngCfg;
} CVI_MODEMNG_S;

#define CVI_MODE_EINITIALIZED      CVI_APPCOMM_ERR_ID(CVI_APP_MOD_MODEMNG,CVI_EINITIALIZED)/**<Initialized already */
#define CVI_MODE_ENOTINIT          CVI_APPCOMM_ERR_ID(CVI_APP_MOD_MODEMNG,CVI_ENOINIT)/**<Not inited */
#define CVI_MODE_EINVAL            CVI_APPCOMM_ERR_ID(CVI_APP_MOD_MODEMNG,CVI_EINTER)/**<Parameter invalid */
#define CVI_MODE_EINTER            CVI_APPCOMM_ERR_ID(CVI_APP_MOD_MODEMNG,CVI_EINTER)/**<Internal error */
#define CVI_MODE_ENULLPTR          CVI_APPCOMM_ERR_ID(CVI_APP_MOD_MODEMNG,CVI_ERRNO_CUSTOM_BOTTOM + 1)/**<Null pointer */
#define CVI_MODE_EINPROGRESS       CVI_APPCOMM_ERR_ID(CVI_APP_MOD_MODEMNG,CVI_ERRNO_CUSTOM_BOTTOM + 2)/**<Operation now in progress */
typedef enum cviEVENT_MODE_E {
    CVI_EVENT_MODEMNG_CARD_REMOVE               = CVI_APPCOMM_EVENT_ID(CVI_APP_MOD_MODEMNG, 0),
    CVI_EVENT_MODEMNG_CARD_AVAILABLE            = CVI_APPCOMM_EVENT_ID(CVI_APP_MOD_MODEMNG, 1),
    CVI_EVENT_MODEMNG_CARD_UNAVAILABLE          = CVI_APPCOMM_EVENT_ID(CVI_APP_MOD_MODEMNG, 2),
    CVI_EVENT_MODEMNG_CARD_ERROR                = CVI_APPCOMM_EVENT_ID(CVI_APP_MOD_MODEMNG, 3),
    CVI_EVENT_MODEMNG_CARD_FSERROR              = CVI_APPCOMM_EVENT_ID(CVI_APP_MOD_MODEMNG, 4),
    CVI_EVENT_MODEMNG_CARD_SLOW                 = CVI_APPCOMM_EVENT_ID(CVI_APP_MOD_MODEMNG, 5),
    CVI_EVENT_MODEMNG_CARD_CHECKING             = CVI_APPCOMM_EVENT_ID(CVI_APP_MOD_MODEMNG, 6),
    CVI_EVENT_MODEMNG_CARD_FORMAT,
    CVI_EVENT_MODEMNG_CARD_FORMATING,
    CVI_EVENT_MODEMNG_CARD_FORMAT_SUCCESSED,
    CVI_EVENT_MODEMNG_CARD_FORMAT_FAILED,
    CVI_EVENT_MODEMNG_CARD_READ_ONLY,
    CVI_EVENT_MODEMNG_CARD_MOUNT_FAILED,
    CVI_EVENT_MODEMNG_RESET,
    CVI_EVENT_MODEMNG_MODESWITCH,
    CVI_EVENT_MODEMNG_MODEOPEN,
    CVI_EVENT_MODEMNG_MODECLOSE,
    CVI_EVENT_MODEMNG_START_REC,
    CVI_EVENT_MODEMNG_STOP_REC,
    CVI_EVENT_MODEMNG_SWITCH_LIVEVIEW,
    CVI_EVENT_MODEMNG_LIVEVIEW_UPORDOWN,
    CVI_EVENT_MODEMNG_LIVEVIEW_ADJUSTFOCUS,
    CVI_EVENT_MODEMNG_START_PIV,
    CVI_EVENT_MODEMNG_START_EMRREC,
    CVI_EVENT_MODEMNG_SCREEN_DORMANT,
    CVI_EVENT_MODEMNG_SETTING,
    CVI_EVENT_MODEMNG_SETTING_LANGUAGE,
    CVI_EVENT_MODEMNG_POWEROFF,
    CVI_EVENT_MODEMNG_PLAYBACK_PLAY             = CVI_APPCOMM_EVENT_ID(CVI_APP_MOD_MODEMNG, 100),
    CVI_EVENT_MODEMNG_PLAYBACK_PROGRESS,
    CVI_EVENT_MODEMNG_PLAYBACK_PAUSE,
    CVI_EVENT_MODEMNG_PLAYBACK_RESUME,
    CVI_EVENT_MODEMNG_PLAYBACK_SEEK,
    CVI_EVENT_MODEMNG_PLAYBACK_SEEKPAUSE,
    CVI_EVENT_MODEMNG_PLAYBACK_FINISHED,
    CVI_EVENT_MODEMNG_PLAYBACK_ABNORMAL,
    CVI_EVENT_MODETEST_START_RECORD             = CVI_APPCOMM_EVENT_ID(CVI_APP_MOD_MODEMNG, 200),
    CVI_EVENT_MODETEST_STOP_RECORD,
    CVI_EVENT_MODETEST_PLAY_RECORD,
    CVI_EVENT_MODEMNG_START_UPFILE,
    CVI_EVENT_MODEMNG_UPFILE_SUCCESSED,
    CVI_EVENT_MODEMNG_UPFILE_FAIL,
    CVI_EVENT_MODEMNG_UPFILE_FAIL_FILE_ERROR,
    CVI_EVENT_MODEMNG_UVC_MODE_START,
    CVI_EVENT_MODEMNG_UVC_MODE_STOP,
    CVI_EVENT_MODEMNG_STORAGE_MODE_PREPAREDEV,
    CVI_EVENT_MODEMNG_PHOTO_SET,
    CVI_EVENT_MODEMNG_RTSP_INIT,
    CVI_EVENT_MODEMNG_RTSP_SWITCH,
    CVI_EVENT_MODEMNG_RTSP_DEINIT,
    CVI_EVENT_MODEMNG_RECODER_STARTSTATU,
    CVI_EVENT_MODEMNG_RECODER_STOPSTATU,
    CVI_EVENT_MODEMNG_RECODER_SPLITREC,
    CVI_EVENT_MODEMNG_RECODER_STARTEVENTSTAUE,
    CVI_EVENT_MODEMNG_RECODER_STOPEVENTSTAUE,
    CVI_EVENT_MODEMNG_RECODER_STARTEMRSTAUE,
    CVI_EVENT_MODEMNG_RECODER_STOPEMRSTAUE,
    CVI_EVENT_MODEMNG_RECODER_STARTPIVSTAUE,
    CVI_EVENT_MODEMNG_RECODER_STOPPIVSTAUE,
#ifdef SERVICES_SPEECH_ON
    CVI_EVENT_MODEMNG_SPEECHMNG_STARTREC,
    CVI_EVENT_MODEMNG_SPEECHMNG_STOPREC,
    CVI_EVENT_MODEMNG_SPEECHMNG_OPENFRONT,
    CVI_EVENT_MODEMNG_SPEECHMNG_OPENREAR,
    CVI_EVENT_MODEMNG_SPEECHMNG_CLOSESCREEN,
    CVI_EVENT_MODEMNG_SPEECHMNG_OPENSCREEN,
    CVI_EVENT_MODEMNG_SPEECHMNG_EMRREC,
    CVI_EVENT_MODEMNG_SPEECHMNG_PIV,
    CVI_EVENT_MODEMNG_SPEECHMNG_CLOSEWIFI,
    CVI_EVENT_MODEMNG_SPEECHMNG_OPENWIFI,
    CVI_EVENT_MODEMNG_START_SPEECH,
    CVI_EVENT_MODEMNG_STOP_SPEECH,
#endif
    CVI_EVENT_MOVIEMODE_BUTT
} CVI_EVENT_MODE_E;

int32_t CVI_MODEMNG_Init(CVI_MODEMNG_CONFIG_S *stModemngCfg);
int32_t CVI_MODEMNG_Deinit();
int32_t CVI_MODEMNG_SendMessage(const CVI_MESSAGE_S *pstMsg);
int32_t CVI_MODEMNG_GetCurMode(uint32_t *ModeId);
int32_t CVI_MODEMNG_GetCurWorkMode(void);
int32_t CVI_MODEMNG_SetParkingRec(bool en);
int32_t CVI_MODEMNG_GetModeState(uint32_t *state);
int32_t CVI_MODEMNG_SetModeState(uint32_t state);
int32_t CVI_MODEMNG_RegisterEvent(void);
int32_t CVI_MODEMNG_LiveViewUp(uint32_t viewwin);
int32_t CVI_MODEMNG_LiveViewDown(uint32_t viewwin);

uint32_t CVI_MODEMNG_GetCardState(void);

bool CVI_MODEMNG_GetInProgress(void);
bool CVI_MODEMNG_GetEmrState(void);

int32_t CVI_MODEMNG_TEST_MAIN_Create(void);
int32_t CVI_MODEMNG_TEST_MAIN_Destroy(void);

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* End of #ifdef __cplusplus */

#endif
