#ifndef _CVI_SPEECHMNG_H_
#define _CVI_SPEECHMNG_H_

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif /* End of #ifdef __cplusplus */

#include <stdint.h>
#include "cvi_appcomm.h"
#include "cvi_speech.h"

#define CVI_SPEECHMNG_EREGISTER_EVENT CVI_APPCOMM_ERR_ID(CVI_APP_MOD_SPEECHMNG, CVI_ERRNO_CUSTOM_BOTTOM)     /**<register event failed */

typedef CVI_SPEECH_SERVICE_PARAM_S CVI_SPEECHMNG_PARAM_S;

typedef enum _CVI_SPEECHMNG_CMD_E
{
    CVI_SPEECHMNG_NONE = 0,
    CVI_SPEECHMNG_SHOW_FRONT,
    CVI_SPEECHMNG_SHOW_REAR,
    CVI_SPEECHMNG_TURN_OFF_SCREEN,
    CVI_SPEECHMNG_OPEN_SCREEN,
    CVI_SPEECHMNG_LOCK_VEDIO,
    CVI_SPEECHMNG_TAKE_PICTURE,
    CVI_SPEECHMNG_TURN_OFF_RECORDING,
    CVI_SPEECHMNG_OPEN_RECORDING,
    CVI_SPEECHMNG_OPEN_WIFI,
    CVI_SPEECHMNG_TURN_OFF_WIFI,
    CVI_SPEECHMNG_BUIT
} CVI_SPEECHMNG_CMD_E;

/** event ID define */
typedef enum cviEVENT_SPEECHMNG_E {
    CVI_EVENT_SPEECHMNG_STARTREC = CVI_APPCOMM_EVENT_ID(CVI_APP_MOD_SPEECHMNG, 0),
    CVI_EVENT_SPEECHMNG_STOPREC,
    CVI_EVENT_SPEECHMNG_OPENFRONT,
    CVI_EVENT_SPEECHMNG_OPENREAR,
    CVI_EVENT_SPEECHMNG_CLOSESCREEN,
    CVI_EVENT_SPEECHMNG_OPENSCREEN,
    CVI_EVENT_SPEECHMNG_EMRREC,
    CVI_EVENT_SPEECHMNG_PIV,
    CVI_EVENT_SPEECHMNG_CLOSEWIFI,
    CVI_EVENT_SPEECHMNG_OPENWIFI,
    CVI_EVENT_SPEECHMNG_BUTT
} CVI_EVENT_SPEECHMNG_E;

int32_t CVI_SPEECHMNG_Init(CVI_SPEECHMNG_PARAM_S* SpeechCfg);
int32_t CVI_SPEECHMNG_DeInit(void);
int32_t CVI_SPEECHMNG_StartSpeech(void);
int32_t CVI_SPEECHMNG_StopSpeech(void);

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* End of #ifdef __cplusplus */

#endif /* _CVI_SPEECHMNG_H_ */