; storage config
[storage]
dev_state   = ; 0:unplugged 1:connecting 2:connected 3:idle
stg_state   = ; 0:unplugged 1:connecting 2:error 3:checking ...
fs_type     =
work_mode   =
dev_port    = "cvi.0"
speed_class =
speed_grade =
dev_type    =
dev_path    = "/dev/mmcblk0p1"
mnt_path    = "/mnt/sd/"

[keymng.key]
key_cnt            = 1
key_type0          = 0
key_id0            = 1
longkey_enable0    = 1
longkey_time0      = 2000

[keymng.grpkey]
enable             = 0
key_idx0           = 0
key_idx1           = 1

[gaugemng]
LowLevel           = 20
UltraLowLevel      = 20

; g-sensor
[gsensor_config]
enable             = 1 ;
enSensitity        = 1 ; 
u32SampleRate      = 0 ;
level              = 1 ;

; wifi
[wifi_config]
enable      = 1 ; 0:disabled 1:enable
mode        = 1 ; 0:STA mode  1: AP mode
ssid        = "cvi_cardv_ap" ; 32 char max
password    = "12345678" ; 32 char max
ssid_hide   = 0 ; 0:hide 1:show
channel     = 6

[sensor_config]
dev_num = 1
cam_num = 1
