#ifndef __CVI_CMD_RECORD_H__
#define __CVI_CMD_RECORD_H__

#define CVI_CMD_CLIENT_ID_RECORD (CVI_MQ_CLIENT_ID_SCS)
//
// Let CVI_CMD_CHANNEL_ID_RECORD equal to servie ID (sensor ID)
//
#define CVI_CMD_CHANNEL_ID_RECORD(rec_id) (0x00 + (rec_id))

typedef enum cvi_cmd_record_e {
    CVI_CMD_RECORD_INVALID = 0,
    CVI_CMD_RECORD_SHUTDOWN = 1,
    CVI_CMD_RECORD_DEBUG = 2,
    CVI_CMD_RECORD_GET_STATUS = 3,
    CVI_CMD_RECORD_RESERVED = 4,
    CVI_CMD_RECORD_REC_START = 7,
    CVI_CMD_RECORD_REC_STOP = 8,
    CVI_CMD_RECORD_PIV_CAPTURE = 9,
    CVI_CMD_RECORD_LOCK_REC_START = 10,
    CVI_CMD_RECORD_LOCK_REC_STOP = 11,
    CVI_CMD_RECORD_EVENT_REC = 12,
    CVI_CMD_RECORD_RTSP_ENABLE = 13,
    CVI_CMD_RECORD_RTSP_DISABLE = 14,
    CVI_CMD_RECORD_NULL0 = 17,
    CVI_CMD_RECORD_NULL1 = 18,
    CVI_CMD_RECORD_RTSP_ADD_FILE_SESSION = 19,
    CVI_CMD_RECORD_RTSP_DELETE_FILE_SESSION = 20,
    CVI_CMD_RECORD_TIMELAPSE_REC_START = 21,
    CVI_CMD_RECORD_TIMELAPSE_REC_STOP = 22,
    CVI_CMD_RECORD_MUTE = 23,
    CVI_CMD_RECORD_DISABLE_MUTE = 24,
    CVI_CMD_RECORD_MAX = 25
} cvi_cmd_record_t;

#endif  // __CVI_CMD_RECORD_H__
