#ifndef __CVI_PLAYER_SERVICE_COMMAND_H__
#define __CVI_PLAYER_SERVICE_COMMAND_H__

#define CVI_PLAYER_SERVICE_CLIENT_ID (CVI_MQ_CLIENT_ID_SVC_0)
#define CVI_PLAYER_SERVICE_CHANNEL_ID(chn_id) (0x00 + (chn_id))

typedef enum {
    CVI_CMD_PLAYER_INVALID = 0,
    CVI_CMD_PLAYER_SHUTDOWN,
    CVI_CMD_PLAYER_DEBUG,
    CVI_CMD_PLAYER_GET_STATUS,
    CVI_CMD_PLAYER_PLAY,
    CVI_CMD_PLAYER_STOP,
    CVI_CMD_PLAYER_PAUSE,
    CVI_CMD_PLAYER_SEEK,
    CVI_CMD_PLAYER_RESET_SIZE,
    CVI_CMD_PLAYER_RESET_POS,
    CVI_CMD_PLAYER_MAX
} CVI_PLAYER_SERVICE_COMMAND_E;

#endif // __CVI_PLAYER_SERVICE_COMMAND_H__
