#pragma once

typedef enum CviFileRecoverEventType
{
    CVI_FILE_RECOVER_EVENT_OPEN_FAILED,
    CVI_FILE_RECOVER_EVENT_RECOVER_START,
    CVI_FILE_RECOVER_EVENT_RECOVER_PROGRESS,
    CVI_FILE_RECOVER_EVENT_RECOVER_FAILED,
    CVI_FILE_RECOVER_EVENT_RECOVER_FINISHED,
} CVI_FILE_RECOVER_EVENT_TYPE_E;

typedef struct CviFileRecoverEvent
{
    CVI_FILE_RECOVER_EVENT_TYPE_E type;
    double value;
} CVI_FILE_RECOVER_EVENT_S;
