; [menu_config]
; video_size  = "1440P"   ; 720P/1080P/1440P/2160P...
; video_loop  = 1         ; 1/3/5 min
; video_codec = "h264"    ; h264/h265
; lap_setime  = 1;        ; 0:off, 1/2/3:s
; audio_enable= 1;        ; 0:off, 1:on
; osd_enable  = 1;        ; 0:off, 1:on


[video_size]
num     = 3
current = 0 
description0    = "CVI_MEDIA_VIDEO_SIZE_2560X1440P30"
value0          = 0
description1    = "CVI_MEDIA_VIDEO_SIZE_1920X1080P30"
value1          = 1
description2    = "CVI_MEDIA_VIDEO_SIZE_1280X720P30"
value2          = 2

[video_loop]
num     = 3
current = 0
description0    = "1MIN"
value0          = 0
description1    = "3MIN"
value1          = 1
description2    = "5MIN"
value2          = 2

[video_codec]
num     = 2
current = 0
description0    = "H264"
value0          = 0
description1    = "H265"
value1          = 1

[lapse_time]
num     = 4
current = 0
description0    = "OFF"
value0          = 0
description1    = "1S"
value1          = 1
description2    = "2S"
value2          = 2
description3    = "3S"
value3          = 3

[audio_enable]
num     = 2
current = 1
description0    = "OFF"
value0          = 0
description1    = "ON"
value1          = 1

[osd_enable]
num     = 2
current = 1
description0    = "OFF"
value0          = 0
description1    = "ON"
value1          = 1

[screen_dormant]
num     = 4
current = 0
description0    = "OFF"
value0          = 0
description1    = "1MIN"
value1          = 1
description2    = "3MIN"
value2          = 2
description3    = "5MIN"
value3          = 3

[key_tone]
num     = 2
current = 1
description0    = "OFF"
value0          = 0
description1    = "ON"
value1          = 1

[fatigue_driving]
num     = 5
current = 1
description0    = "OFF"
value0          = 0
description1    = "1HOUR"
value1          = 1
description2    = "2HOUR"
value2          = 2
description3    = "3HOUR"
value3          = 3
description3    = "4HOUR"
value3          = 4

[speed_stamp]
num     = 2
current = 1
description0    = "OFF"
value0          = 0
description1    = "ON"
value1          = 1

[GPS_stamp]
num     = 2
current = 1
description0    = "OFF"
value0          = 0
description1    = "ON"
value1          = 1

[Speed_Unit]
num     = 2
current = 0
description0    = "KMH"
value0          = 0
description1    = "MPH"
value1          = 1

[RearCam_Mirror]
num     = 2
current = 0
description0    = "OFF"
value0          = 0
description1    = "ON"
value1          = 1

[Language]
num     = 2
current = 0
description0    = "CHN"
value0          = 0
description1    = "ENG"
value1          = 1

[Time_Format]
num     = 2
current = 1
description0    = "12"
value0          = 0
description1    = "24"
value1          = 1

[Time_Zone]
num     = 5
current = 0
description0    = "CHN"
value0          = 0
description1    = "ENG"
value1          = 1
description1    = "UNI"
value1          = 2
description1    = "JAP"
value1          = 3
description1    = "EGP"
value1          = 4

[Frequence]
num     = 2
current = 0
description0    = "50Hz"
value0          = 0
description1    = "60Hz"
value1          = 1

[Parking]
num     = 2
current = 0
description0    = "OFF"
value0          = 0
description1    = "ON"
value1          = 1