; common config
[common]
mnt_path = "/mnt/sd/"


; dtcf config
[dtcf]
root_path          = "CARDV"
pre_alloc_cnt      = "100";
pre_alloc_unit     = "3110400";unit: byte
sharepercent       = 95
warning            = 4
guaranteed         = 5

[dir_name]
dir_name0 = "EMR"
dir_name1 = ""
dir_name2 = "MOVIE"
dir_name3 = ""
dir_name4 = ""
dir_name5 = ""
dir_name6 = "EMR_b"
dir_name7 = ""
dir_name8 = "MOVIE_b"
dir_name9 = ""
dir_name10 = ""
dir_name11 = ""
dir_name12 = "PHOTO"
dir_name13 = "PHOTO_b"

[prealloc]
enable = 0
reserve_memory = 5 ;percentage
pre_alloc_cnt_dir_0       = "5"; percentage
pre_alloc_unit_dir_0      = "120";unit: MB
pre_alloc_cnt_dir_1       = "";
pre_alloc_unit_dir_1      = "";unit: MB
pre_alloc_cnt_dir_2       = "40"; percentage
pre_alloc_unit_dir_2      = "120";unit: MB
pre_alloc_cnt_dir_3       = "";
pre_alloc_unit_dir_3      = "";unit: MB
pre_alloc_cnt_dir_4       = "";
pre_alloc_unit_dir_4      = "";unit: MB
pre_alloc_cnt_dir_5       = "";
pre_alloc_unit_dir_5      = "";unit: MB
pre_alloc_cnt_dir_6       = "5";percentage
pre_alloc_unit_dir_6      = "100";unit: MB
pre_alloc_cnt_dir_7       = "";
pre_alloc_unit_dir_7      = "";unit: MB
pre_alloc_cnt_dir_8       = "40";percentage
pre_alloc_unit_dir_8      = "100";unit: MB
pre_alloc_cnt_dir_9       = "";
pre_alloc_unit_dir_9      = "";unit: MB
pre_alloc_cnt_dir_10      = "";
pre_alloc_unit_dir_10     = "";unit: MB
pre_alloc_cnt_dir_11      = "";
pre_alloc_unit_dir_11     = "";unit: MB
pre_alloc_cnt_dir_12      = "2.5";percentage
pre_alloc_unit_dir_12     = "";unit: MB
pre_alloc_cnt_dir_13      = "2.5";percentage
pre_alloc_unit_dir_13     = "";unit: MB


